name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "5.4.0"

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Check Lua format
        uses: JohnnyMorganz/stylua-action@v3
        with: 
          args: --check .


      - name: Check Lua warnings and errors
        run: luacheck .


